### ISSUE TITLE
Video Player (Portrait Mode)

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-Android#318]
@filbabic 

Is working on a portrait mode for the video player 

![Screenshot_1609751249](https://user-images.githubusercontent.com/5320361/103525063-e9c85c00-4e7e-11eb-94a4-91d21160644e.png)
![Screenshot_1609751256](https://user-images.githubusercontent.com/5320361/103525069-ecc34c80-4e7e-11eb-82f2-5c9bac1f4e6c.png)
![Screenshot_1609751284](https://user-images.githubusercontent.com/5320361/103525072-ed5be300-4e7e-11eb-8711-001f24418693.png)
![Screenshot_1609751271(1)](https://user-images.githubusercontent.com/5320361/103525074-edf47980-4e7e-11eb-9100-031a7e6913b4.png)
![Screenshot_1609751429(1)](https://user-images.githubusercontent.com/5320361/103525076-ee8d1000-4e7e-11eb-9b7f-f9fcf10cb4b3.png)

**Comment by luke-freeman** [comment]
@filbabic 

- What do you think about hiding the text labels on the video controls on portrait and just having icons?
- The controls for speed/quality need a different layout in portrait. Can they fill more vertical space?
- I think the episode switcher works in portrair with the horizontal scroll (as-is). What do you think?

**Comment by filbabic** [comment]
Hey Luke!

* We can supply different UI depending on the orientation of the screen. That being said, we can hide all the labels and just have icons, re-arrange them, move them around etc.
* Instead of having the controls for speed/quality horizontally scrollable, we could flip the orientation here too, and make them vertically scrollable. It would look like three columns, one for each option.
* Yeah, the episode switcher works as-is, as it's a horizontally scrollable container of up to three elements per column.

**Comment by filbabic** [comment]
@luke-freeman I've done more work on the Portrait mode of the player feature, and this is the result:
https://drive.google.com/drive/u/1/folders/1EKGD_Q0cwQxeaCNdFSYEIJQYoQRXolKj

As you can see, I've removed the text from the options, when in portrait mode. I changed the option orientation, so that now it works nicely, and the user can pick and choose their settings.

I've also fixed the centering of the title in the toolbar as the navigation button pushed it to the right side with padding.

**Let me know if you feel like this is good enough UI to possibly prepare as a release in February. I can also build an APK and give it to you to test the feature if you'd like.**

I'm aiming to implement this and ship it in February, to keep our releases going. I'll try to focus on mostly UI-related improvements in the next few months, so anything you feel is going to improve our experience will be prioritized.

I saw some tickets for changing the navigation, to have 4 tabs (current + settings) instead of three. This is also something I feel should be easy enough to change.
